### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by cursorial** [nicholas-ochoa/OpenSC2K#1]
Are you looking for people to contribute to this? If so - it might make sense to start creating issues around features that need implementing and bugs that need fixing?

I'd love to contribute if possible :)

A couple of things that could do with implementing just from looking at screenshots:

- GUI/HUD
- Menu Screen

**Comment by proustibat** [comment]
Good idea! Maybe you could also create a roadmap with to-dos to share the features you wanna develop?
For issues, labels should be helpful. 
Would be glad to contribute to fix some bugs
