### ISSUE TITLE
Extract and utilize original game assets

### ISSUE THREAD

**Issue by nicholas-ochoa** [nicholas-ochoa/OpenSC2K#28]
- [X] Extract static tiles (LARGE.DAT)
- [X] Extract palette
- [X] Animated tiles (palette rotation)
- [x] Generate PNG tile maps from original game artwork
- [x] Small/Medium tiles (SMALLMED.DAT)
- [ ] Game audio files (wav)
- [ ] Game music (JS midi?)
- [ ] Support multiple versions (Win95, DOS) and common install paths (Steam, GOG)
- [ ] Game artwork (BMP to PNG conversion?)
- [ ] Supplemental files from the game (text/strings, newspaper text)

**Comment by cursorial** [comment]
Game music can be played with:- 

PixiJS plugin: https://github.com/pixijs/pixi-sound

or

PhaserIO includes a sound module: https://phaser.io/examples/v2/audio/sound-complete

**Comment by rage8885** [comment]
The re-write broken pretty much all of this code, I'm looking at fixing it over the next few days so I can finally remove the assets

**Comment by pranaygp** [comment]
Is it perhaps possible to convert the MIDI files first (to m3 or wav) and then use them?

**Comment by dfloer** [comment]
I know @rage8885 already know about this, but if anyone else is looking to help, I cleaned up the documentation around the sprite file specs and made it public.

https://github.com/dfloer/SC2k-docs/blob/master/sprite%20data%20spec.md
