### ISSUE TITLE
Hosted deployment

### ISSUE THREAD

**Issue by pranaygp** [nicholas-ochoa/OpenSC2K#44]
Hey, this repo is awesome. I managed to get it to run locally super easily, and then, just as easily, managed to deploy it to [now](https://now.sh). I threw up a deployment of the latest `master` up here:

https://simcity.now.sh/

And I think it could be awesome to keep this (or another deployment of this) up to date as changes are made so people can try it without having to run it locally. I'm happy to transfer ownership of (https://simcity.now.sh/) or take it down or help you build and maintain a deployment pipeline to have an active deployment of the game as you continue to build core features to this (obviously depends on how actively you're working on this project).

**Comment by pranaygp** [comment]
I'm happy to help build and maintain some sort of continuous deployment thing for the project (Disclaimer: I also happen to work at Zeit, where https://simcity.now.sh/ is hosted)

**Comment by solipsist01** [comment]
Perhaps it's also a good idea to have a dockerfile so people can pull and host it everywhere they like :)
I took the liberty to create one, and have made a pull request.

I made an automated build at the docker hub from this dockerfile and it works :)
docker run --name=opensc2k -d -p 3000:3000 --restart=always solipsist01/opensc2k

**Comment by 1j01** [comment]
[Netlify](https://www.netlify.com/) is another nice option; I only found it recently, but it's really easy to set up initially, and they have a nice option to generate "deploy preview" URLs for pull requests (not necessarily as easy to set up?)

My biggest complaints are that 1. there are a few places in the UI where it should direct you to other places, like after changing deploy settings it should link to where you can trigger a deploy manually, and 2. there's some problem with multiple domains and HTTPS where it just doesn't seem to trigger provisioning a new certificate to include new domains.
(1 is pretty minor and I don't think 2 would affect you.)
