### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by cursorial** [nicholas-ochoa/OpenSC2K#8]
We should create a main menu with the following options to replicate what we see in SimCity when the game starts up.

The options should include:

- Load Saved City
- Start New City
- Edit New Map
- Load Scenario
- Quit

Some of these options won't have implementations behind them yet, such as loading scenarios, although they could at least be created for now. It would be good to create a button component system here that can also be used for the GUI in game to keep everything consistent across the codebase.

After taking a look at the code I've noticed that we're missing some stuff, we'll need some form of game state management - it may be worth looking into using a game library of some sort so we don't have to implement that ourselves. I'd suggest [Phaser](http://phaser.io). This would also help us to structure the code a bit better since currently it looks like there's a lot being handled in [game.js](https://github.com/rage8885/OpenSC2K/blob/master/js/game.js)

These are just the options from the original game, it may be worth adding other options - for example a 'Settings' option for selecting resolution/changing in-game volume, etc.

Another potential would be to set up some way for people to share maps that they've created, scenarios, assets, etc. See: OpenTTD. Would be good to allow for mods, etc.

Finally, it would be cool to see a multiplayer version of the game, not sure how far we want to move outside the scope but OpenTTD also allows for multiplayer online, it could be cool to see similar here.

**Comment by rage8885** [comment]
Some of the initial framework is in place for this (the title.js scene and ui/ui.js scene. Ultimately, I'm planning to use [Vue](https://github.com/vuejs/vue) along with the [iView UI Toolkit](https://github.com/iview/iview) to build much of the interface. I explored doing a UI entirely within the game engine but the performance considerations (even using Phaser) make that less of an option - better to spend those cycles on the simulation or somewhere else.

**Comment by cursorial** [comment]
This is actually a much better idea to be fair, no point running it through
a rendering engine.
